### ISSUE TITLE
Cannot upload files

### ISSUE THREAD

**Issue by FredrikKarlssonSpeech** [humlab-speech/humlab-speech-deployment#37]
This is what I get when I try to clone from gitlab

```
>  git clone https://gitlab.speech.humlab.umu.se/fredrik.k.karlsson_at_umu.se/fk-project.git
Cloning into 'fk-project'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.speech.humlab.umu.se/fredrik.k.karlsson_at_umu.se/fk-project.git/'
> git clone git@gitlab.speech.humlab.umu.se:fredrik.k.karlsson_at_umu.se/fk-project.git
Cloning into 'fk-project'...
ssh: connect to host gitlab.speech.humlab.umu.se port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
>  git clone https://gitlab.speech.humlab.umu.se/fredrik.k.karlsson_at_umu.se/fk-project.git
Cloning into 'fk-project'...
Username for 'https://gitlab.speech.humlab.umu.se': frkkan96
Password for 'https://frkkan96@gitlab.speech.humlab.umu.se': 
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.speech.humlab.umu.se/fredrik.k.karlsson_at_umu.se/fk-project.git/'
```

Connected via VPN.

**Comment by johanvonboer** [comment]
Yes, there are a few limitations with the way we are using Gitlab now, they are:

1) All git operations have to be done over HTTPS, since SSH conflicts with the 'regular' SSH to the server. It would probably be possible to set this up (perhaps with some help from ITS) so that all SSH requests towards the gitlab subdomain is routed through to gitlab and not intercepted by the server SSH daemon, but that's not the case right now, so it's HTTPS only atm.

2) When doing git operations you need to use a personal access token. Since Gitlab is configured to use SAML authentication towards Keycloak, and since SAML requires a user with a browser (as it is now it's actually the browser which 'carries' the authentication data as it's being redirected), it can't do any authentication on the behalf of the user. Perhaps there is some way to configure things to make that work, but I'm not super hopeful about it.

To use a personal access token, click the user/profile menu -> preferences -> Access Tokens and then generate a new one with the proper access and then insert it into the clone URL like: `git clone https://johan.von.boer_at_umu.se:PAT-GOES-HERE@gitlab.speech.humlab.umu.se/johan.von.boer_at_umu.se/test-1a`

The username doesn't actually seem to matter, it just needs to be there. So it can be 'root' or 'user' or whatever.

**Comment by johanvonboer** [comment]
Forgot to mention that VPN shouldn't be required, and using it will give you terrible performance.

**Comment by FredrikKarlssonSpeech** [comment]
Ok, transfering  now..  The
