### ISSUE TITLE
libgit2 - the Git linkable library

### ISSUE THREAD

**Issue by roger-mahler** [humlab-speech/humlab-speech-deployment#43]
https://libgit2.org/
https://www.pygit2.org/
https://github.com/libgit2/libgit2#language-bindings
https://github.com/ropensci/git2r

**Comment by johanvonboer** [comment]
I appreciate you trying to help but the problem is not that there isn't git libraries available (I'm currently using the node lib simple-git), but that git itself does not provide machine-readable error codes. It only spits out a human readable error message, which I suspect is subject to change. It would be great if there were also error codes similar to how it's done with HTTP, but that doesn't seem to be the case. This means that I have to do string matching on the human readable error messages to figure out what the problem was, which is not ideal.
